### ISSUE TITLE
Can't build with Xcode 13.3.1

### ISSUE THREAD

**Issue by Turtleted21** [dpa99c/cordova-plugin-firebasex-test#23]
Hello,
I can't build I have these 3 errors with Xcode 13.3.1

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIColor.h:13:2: fatal error: 
      file
      '/Users/macmini/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2T0KU6C7S1FQS/CoreImage-2L8M44C0CYIPM.pcm'
      is not a valid precompiled module file
#import <CoreImage/CoreImage.h>
 ^
1 error generated.
While building module 'FBLPromises' imported from /Users/macmini/Documents/EADV_IPAD_IOS9_8.2/cordova-plugin-firebasex-test/platforms/ios/Pods/GoogleUtilities/GoogleUtilities/Environment/URLSessionPromiseWrapper/NSURLSession+GULPromises.m:20:
In file included from <module-includes>:1:
/Users/macmini/Documents/EADV_IPAD_IOS9_8.2/cordova-plugin-firebasex-test/platforms/ios/Pods/Target Support Files/PromisesObjC/PromisesObjC-umbrella.h:2:9: fatal error: 
      could not build module 'UIKit'
#import <UIKit/UIKit.h>
 ~~~~~~~^
2 errors generated.
/Users/macmini/Documents/EADV_IPAD_IOS9_8.2/cordova-plugin-firebasex-test/platforms/ios/Pods/GoogleUtilities/GoogleUtilities/Environment/URLSessionPromiseWrapper/NSURLSession+GULPromises.m:20:9: fatal error: 
      could not build module 'FBLPromises'
#import <FBLPromises/FBLPromises.h>
 ~~~~~~~^
3 errors generated.
```
![Capture d’écran 2022-05-12 à 14 37 33](https://user-images.githubusercontent.com/46889785/168076409-3ed0787b-8bd9-46c6-b98f-de77be567b89.png)

**Comment by dpa99c** [comment]
Test on a real iOS device, not the iOS Simulator and run `pod repo update` to ensure your local Cocoapods repo is up-to-date
